package com.ceair.cxf.ws.java.client.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-03-02T09:35:31.047+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://server.java.ws.cxf.ceair.com/", name = "MobileAddress")
@XmlSeeAlso({ObjectFactory.class})
public interface MobileAddress {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAddressByMobile", targetNamespace = "http://server.java.ws.cxf.ceair.com/", className = "com.ceair.cxf.ws.java.client.stub.GetAddressByMobile")
    @WebMethod
    @ResponseWrapper(localName = "getAddressByMobileResponse", targetNamespace = "http://server.java.ws.cxf.ceair.com/", className = "com.ceair.cxf.ws.java.client.stub.GetAddressByMobileResponse")
    public java.lang.String getAddressByMobile(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
